language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

services:
  - postgresql

addons:
  apt:
    packages:
      - cmake

before_script:
  - psql -c 'create database mtls;' -U postgres
  - pip3 install pipenv

script:
  - make test
